config/routes.rb
Rails.application.routes.draw do
  root "tables#new"
  resources :tables, only: [:new, :create] do
    collection do
      get :call
    end
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :table
  validates :content, presence: true
end

app/models/table.rb
class Table < ApplicationRecord
  has_many :messages
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    last_stamp_ids = params[:id]
    i = 1
    @messages = []
    last_stamp_ids.each do |id|
      message = Message.where(table_id: "#{i}").where("id >= ?", id).last
      @messages[i - 1] = message
      i += 1
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_table
  
  def index
    @message = Message.new
    @messages = Message.all.order(id: "DESC")
    @sidemessages = Message.order(id: "DESC").limit(10)
  end
  def create
    @message = Message.create(message_params)
    respond_to do |format|
      format.html {redirect_to table_messages_path(@table.id)}
      format.json
    end
  end


  private
  def message_params
    params.require(:message).permit(:content, :stamp).merge(table_id: @table.name)
  end

  def set_table
    @table = Table.find(params[:table_id])
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController

  def new
    @table = Table.new
  end

  def create
    @table = Table.new(table_params)
    if @table.save
      redirect_to table_messages_path(@table.id)
    else
      render :new
    end
  end

  def call
  end

  private
  def table_params
    params.require(:table).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RestoChat
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/messages/_emoji.html.haml
.EmojiField
  .Emojies.Hidden
    .EmojiStep
      .Emoji 
        &#x1f604;
      .Emoji
        &#x1f60a;
      .Emoji
        &#x1f970;
    .EmojiStep
      .Emoji
        &#x1f60b;
      .Emoji
        &#x1f63b;
      .Emoji
        &#x1f60f;
    .EmojiStep
      .Emoji
        &#x1f60d;
      .Emoji
        &#x1f973;
      .Emoji
        &#x1f496;
    .EmojiStep
      .Emoji
        &#x1f495;
      .Emoji
        &#x1f44d;
      .Emoji
        &#x1f44f;
    .EmojiStep
      .Emoji
        &#x1f37b;
      .Emoji
        &#x1f389;
      .Emoji
        &#x1f917;

app/views/messages/_head_bar.html.haml
.Header
  .RestoName
    .RestoName__main
      StarBuckers 

app/views/messages/_main_chat.html.haml
.RestoChat
  .StampChat
    - 8.times do |i|
      - i += 1
      %div{class: "Hidden StampChat__table#{i}"}
        - if messages.find_by(table_id: "#{i}")
          - message = messages.find_by(table_id: "#{i}")
          .TableMessage{data: {stamp: {id: message.id}}}
            = message.stamp

app/views/messages/_message.html.haml
.MessageBox
  .Message
    .Message__text
      = message.content

app/views/messages/_side_bar.html.haml
.SideBar
  .MessageField
    .MessageBox
      - @sidemessages.each do |message|
        .Message
          .Message__text
            = message.content
          .Message__tableNo
            tableNo,
            = message.table_id

  .Form{data:{id: @table.name}}
    = render "emoji"
    =form_with( model: [@table, @message], local: true, id: "new_message")do |f|
      .FormContent
        = f.text_field :content, class: 'FormContent__inputContent', autofocus: true
        = f.text_field :stamp, class: 'FormContent__inputStamp Hidden'
        = icon( 'fa', 'smile', class: "EmojiBtn")
      = button_tag type: 'submit', class: 'Form__submit' do
        = icon('fa', 'paper-plane', class: 'SubmitIcon')
  = link_to call_tables_path, class: "Cashier" do
    お会計

app/views/messages/index.html.haml
.Wrapper
  .MainChat
    -# = render "head_bar"
    = render partial: "main_chat", locals: {messages: @messages}
  .SideChat
  = render "side_bar"

app/views/tables/_form.html.haml
.TopContentForm
  = form_with model: @table, local: true do |f|
    .TopContentForm__text
      ご来店ありがとうございます。
    .TableForm
      .TableForm__tableSelect
        着席されたテーブル番号を選択して下さい
        = f.select :name, {'Table No.1': 1,'Table No.2': 2,'Table No.3': 3,'Table No.4': 4,'Table No.5': 5,'Table No.6': 6,'Table No.7': 7,'Table No.8': 8}, { include_blank: '選択してください'}, { class: 'TableForm__tableSelect__box', required: true}
      -# .TableForm__btn.HiddenBtn
      -#   = f.submit '参加する'
      .Checkbox
        %input.Checkbox__box{type: "checkbox" }
          = link_to "利用規約", "#"
          に同意し、
          %br
          チャットに参加しますか？
    = f.submit 'チャットに参加する', class: 'TableFormBtn HiddenBtn'

app/views/tables/_head_title.html.haml
.Shop
  .Shop__name
    Resto-Chat

app/views/tables/call.html.haml
.WrapperTable
  .TopContent
    .CallContent
      .CallMessage__wait
        係りの者が参ります。
        %br
        そのままお待ちください
      .CallMessage__thanks
        本日はご来店いただき誠にありがとうございました。
        %br
        またのお越しをお待ちしています。
      .CallBtn
        = link_to root_path, class: "ToppageBtn" do
          TOPへ

app/views/tables/new.html.haml
.WrapperTable
  .TopContent
    = render 'head_title'
    = render 'form'